### ISSUE TITLE
The order of labels issue

### ISSUE THREAD

**Issue by guosoun** [anAcc22/another_graph_editor#3]
If the nodes are numbered from 1 to n, and n is a two-digit number, then Current Nodes will sort the nodes in lexicographical order, such as `1 10 2 3 4 5 6 7 8 9`, while the order of labels given in the problem is often `1 2 3 4 5 6 7 8 9 10`, which makes editing labels very annoying.

One solution I came up with is to add a switch to adjust the sorting method, switching between lexicographical order and numerical order from smallest to largest. However, when there are non-numerical values in Current Nodes, the numerical order from smallest to largest should be disabled

**Comment by guosoun** [comment]
Thank you for your quick response and the proposed workaround; I think it’s a great solution! I am looking forward to the development of the new UI. Thanks again for your support and efforts!

**Comment by guosoun** [comment]
Thank you for your quick response and the proposed workaround; I think it’s a great solution! I am looking forward to the development of the new UI and trying out more sorting options. Thanks again for your support and efforts!

**Comment by anAcc22** [comment]
It has just been implemented, do let me know if the new behavior is weird/buggy (you might have to use ctrl+shift+r if the change doesn't show up right away). Thanks for trying out this tool and your feedback/suggestions are always welcome!
