### ISSUE TITLE
Multiple edges between same nodes are not handled correctly

### ISSUE THREAD

**Issue by MuhammadSawalhy** [anAcc22/another_graph_editor#4]
If two edges are added between the same two nodes they don't show as two edges, maybe both the edges are above each other but we need to see them if possible!
 
![image](https://github.com/user-attachments/assets/bf2c5b5a-a1ca-4fd2-ab71-441f4ee276bd)

Moreover, the bridges are not calculated correctly as in this image. The edge $(1,2)$ is not a bridge as I understand.

![image](https://github.com/user-attachments/assets/28e2a486-e470-4a8f-8219-824eb76e5b5c)

**Comment by anAcc22** [comment]
Hi, currently only simple graphs are supported (i.e., no self loops and multiedges), so even if you wrote (1, 2), (1, 2), only one edge would be stored. Sry about that. Eventually, I'll add multiedge support.

You can try https://cp-tool-app.vercel.app/graph-editor for now; I believe this tool has the multiedge support you need.

**Comment by MuhammadSawalhy** [comment]
Hope you find a time for more features. I may open a PR for that!

**Comment by anAcc22** [comment]
Hey, it's been a while, but multiedge support is finally here. Feel free to check it out, find bugs, etc.

**Comment by Tyruetrue** [comment]
Can it be improved? Because sometimes our graph is undirected and sometimes we need multiple edges. It might be better if we can switch between these two modes.

**Comment by Tyruetrue** [comment]
Some data like `1 2,2 1` ,this situation will be very troublesome to deal with

**Comment by anAcc22** [comment]
Sure, no problem, I've added a toggle so you can switch back to the original non-multiedge mode if you want. By default, multiedge mode is enabled because that's probably what most people expect.

**Comment by Tyruetrue** [comment]
thx!!
