### ISSUE TITLE
new feature needed

### ISSUE THREAD

**Issue by Tyruetrue** [anAcc22/another_graph_editor#5]
Can you add a new feature, click on the dot to make it fix itself, we need a similar feature, thanks

**Comment by anAcc22** [comment]
Do you mean like [this](https://csacademy.com/app/graph_editor/)? Sure, I could add a setting to fix/unfix marked nodes. I'll add it after I'm done with multiedge support.

**Comment by Tyruetrue** [comment]
> 你的意思是像[这样吗](https://csacademy.com/app/graph_editor/)？当然，我可以添加一个设置来修复/取消修复标记节点。完成多边支持后我会添加它。
> 
> 更新：
> 
> 我添加了一个名为“固定模式”的新模式，当它被激活时，标记的节点将保持固定位置。

Yes this is the mode we want,thx
