### ISSUE TITLE
bug: it thinks there's an edge, but there's no edge

### ISSUE THREAD

**Issue by lrvideckis** [anAcc22/another_graph_editor#7]
try pasting in:

```
7 17
1 2
```
to the edges section, then drag node `1` around. It acts as if there's an edge 1<->7

my guess is the bug is somewhere here https://github.com/anAcc22/another_graph_editor/blob/main/src/components/animateGraphEdges.ts#L491-L500 and somehow `isEdge` variable is set to true, when it should be false

**Comment by lrvideckis** [comment]
if you change `17` to a single digit number (!= 1,2,7) then there's no bug

**Comment by anAcc22** [comment]
You're right, the bug was at that spot... But it's been fixed now. Thanks for the clear reproduction steps too!

**Comment by lrvideckis** [comment]
thx for the fix, and for the great tool! I use it all the time

**Comment by anAcc22** [comment]
I'll close this issue for now. Feel free to open new ones if you find more bugs.
